# Generated by Django 2.1.5 on 2019-01-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
